### ISSUE TITLE
sdk5.2.0：viewpage with fragment ,when switch tab，occur error！

### ISSUE THREAD

**Issue by yovenny** [hotmobmobile/hotmob-android-sdk#30]
java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference
        at com.hotmob.sdk.ad.c.run(SourceFile:9)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by hotmob-kenwong** [comment]
Can you give me more Hotmob Log for tracing?
You can enable Hotmob SDK Log by setting debug to true. Then give the log when switching the tab

**Comment by yovenny** [comment]
**I have three tab，when tap tab1 and tab2，then tap back to tab1，occur error，it seems happen hide banner**、

**Comment by yovenny** [comment]
**the same operation，somtimes also cause another error，when tap tab2 to tab1**

EXCEPTION: main
    **Process: gt.farm.eigaland.lab, PID: 3842
    java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.schedule(Timer.java:248)
        at com.hotmob.sdk.ad.HotmobBanner.m(SourceFile:16)
        at com.hotmob.sdk.ad.HotmobBanner.onPageFinished(SourceFile:3)
        at com.hotmob.sdk.ad.webview.AdWebView.onPageFinished(SourceFile:1)
        at com.hotmob.sdk.ad.webview.AdWebViewClient.onPageFinished(SourceFile:6)
        at jY.c(PG:230)
        at zn.handleMessage(PG:72)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)**

**Comment by hotmob-kenwong** [comment]
> **I have three tab，when tap tab1 and tab2，then tap back to tab1，occur error，it seems happen hide banner**、
> 
> 2019-09-05 09:48:27.663 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> [launch_popup] is set as resume Interstitial.
> 2019-09-05 09:48:27.807 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> App resume. Show resume Interstitial.
> 2019-09-05 09:48:27.807 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobInterstitial] <AD_LOAD> [launch_popup] loadAd() starts now!
> 2019-09-05 09:48:29.242 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobInterstitial] <AD_LOAD> [launch_popup] Ad received, start rendering
> 2019-09-05 09:48:39.042 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> After Overlay hide, page changed, leave for change page reload logic.
> 2019-09-05 09:48:39.195 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Change page [] -> [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:48:39.195 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show page [MovieGridRecyclerFragment@63784639] banners.
> 2019-09-05 09:48:39.195 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> There is no banner on page [MovieGridRecyclerFragment@63784639]
> 2019-09-05 09:48:43.649 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Set auto reload with AdView [eigaland_android_showing_test_movie_ad] on page [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:48:43.649 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@63784639] now has 1 ads.
> 2019-09-05 09:48:43.649 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@63784639] is showing now, load ad for [eigaland_android_showing_test_movie_ad] now.
> 2019-09-05 09:48:43.649 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] loadAd() starts now!
> 2019-09-05 09:48:43.666 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Set auto reload with AdView [eigaland_android_showing_test_dynamic] on page [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:48:43.666 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@63784639] now has 2 ads.
> 2019-09-05 09:48:43.666 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@63784639] is showing now, load ad for [eigaland_android_showing_test_dynamic] now.
> 2019-09-05 09:48:43.666 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_dynamic] loadAd() starts now!
> 2019-09-05 09:48:45.338 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_dynamic] Ad received, start rendering
> 2019-09-05 09:48:45.366 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] Ad received, start rendering
> 2019-09-05 09:49:13.522 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Change page [MovieGridRecyclerFragment@63784639] -> [MovieGridRecyclerFragment@151762972].
> 2019-09-05 09:49:13.522 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show page [MovieGridRecyclerFragment@151762972] banners.
> 2019-09-05 09:49:13.523 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> There is no banner on page [MovieGridRecyclerFragment@151762972]
> 2019-09-05 09:49:13.523 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Hide page [MovieGridRecyclerFragment@63784639] banners.
> 2019-09-05 09:49:13.523 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Hide banner [eigaland_android_showing_test_movie_ad] on page [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:49:13.524 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Hide banner [eigaland_android_showing_test_dynamic] on page [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:49:13.525 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] hide immediately.
> 2019-09-05 09:49:13.525 2443-2851/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_dynamic] already hidden.
> 2019-09-05 09:49:15.483 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Set auto reload with AdView [eigaland_android_upcoming_test_movie_ad] on page [MovieGridRecyclerFragment@151762972].
> 2019-09-05 09:49:15.483 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@151762972] now has 1 ads.
> 2019-09-05 09:49:15.483 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@151762972] is showing now, load ad for [eigaland_android_upcoming_test_movie_ad] now.
> 2019-09-05 09:49:15.483 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_upcoming_test_movie_ad] loadAd() starts now!
> 2019-09-05 09:49:15.492 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Set auto reload with AdView [eigaland_android_upcoming_test_dynamic] on page [MovieGridRecyclerFragment@151762972].
> 2019-09-05 09:49:15.492 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@151762972] now has 2 ads.
> 2019-09-05 09:49:15.492 2443-2443/gt.farm.eigaland.lab I/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Page [MovieGridRecyclerFragment@151762972] is showing now, load ad for [eigaland_android_upcoming_test_dynamic] now.
> 2019-09-05 09:49:15.492 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_upcoming_test_dynamic] loadAd() starts now!
> 2019-09-05 09:49:16.410 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_upcoming_test_movie_ad] Ad received, start rendering
> 2019-09-05 09:49:16.424 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_upcoming_test_dynamic] Ad received, start rendering
> 2019-09-05 09:49:34.135 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] already hidden.
> 2019-09-05 09:49:34.136 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_dynamic] already hidden.
> 2019-09-05 09:49:34.482 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Change page [MovieGridRecyclerFragment@151762972] -> [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:49:34.483 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show page [MovieGridRecyclerFragment@63784639] banners.
> 2019-09-05 09:49:34.483 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show banner [eigaland_android_showing_test_movie_ad] on page [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:49:34.485 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show banner [eigaland_android_showing_test_dynamic] on page [MovieGridRecyclerFragment@63784639].
> 2019-09-05 09:49:34.485 2443-2868/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] loadAd() starts now!
> 2019-09-05 09:49:34.486 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Hide page [MovieGridRecyclerFragment@151762972] banners.
> 2019-09-05 09:49:34.486 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Hide banner [eigaland_android_upcoming_test_movie_ad] on page [MovieGridRecyclerFragment@151762972].
> 2019-09-05 09:49:34.486 2443-2869/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_dynamic] loadAd() starts now!
> 2019-09-05 09:49:34.487 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Hide banner [eigaland_android_upcoming_test_dynamic] on page [MovieGridRecyclerFragment@151762972].
> 2019-09-05 09:49:34.489 2443-2443/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_upcoming_test_movie_ad] hide immediately.
> 2019-09-05 09:49:34.493 2443-2871/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_upcoming_test_dynamic] already hidden.

I can't see any abnormality in this log.
Also, the NullPointer occurs in "com.hotmob.sdk.ad.c.run(SourceFile:9)". I can't trace back the file "c" and line "9".

Cannot handle this issue at this moment.

**Comment by hotmob-kenwong** [comment]
We have a ViewPager with Fragments on a testing demo app installed SDK 5.1.3 and we cannot reproduce the above issues.

I suspected that the exception may be triggered by other exception from your app. I recommend you send me a testing build in debug mode and ProGuard off for us to study.

**Comment by yovenny** [comment]
dou you try hotmobBanner.bindToView in adpater with autoLoad&setCurrentPage？，i think sdk should strong check timer. hasCancel() before cancel(),viewGroup.isNull() befor setHeight().

but i don't know what's code let it hasCancel() or isNull、
from：
1.java.lang.IllegalStateException: Timer already cancelled.
2.java.lang.NullPointerException: Attempt to write to field 'int 

sdk5.1.3 alse cause this error
emmm...., I will continue to look for what happen to this problem.

**Comment by hotmob-kenwong** [comment]
> dou you try hotmobBanner.bindToView in adpater with autoLoad&setCurrentPage？，i think sdk should strong check timer. hasCancel() before cancel(),viewGroup.isNull() befor setHeight().
> 
> but i don't know what's code let it hasCancel() or isNull、
> from：
> 1.java.lang.IllegalStateException: Timer already cancelled.
> 2.java.lang.NullPointerException: Attempt to write to field 'int
> 
> sdk5.1.3 alse cause this error
> emmm...., I will continue to look for what happen to this problem.

Thanks.

I will try to add the suggested handling. I will add checking to check if the Banner has parent view after onPageFinished() in later version. 
But as I cannot reproduce it I cannot be sure that it fixes the problem.

And, we have the following test case and there is no error:

Fragment A:
bindToView() is called in RecycleViewAdapter.onBindViewHolder()
HotmobReloadManager.instance.setAutoReload(ad1, "home")

Fragment B: 
bindToView() is called in onCreate()
HotmobReloadManager.instance.setAutoReload(banner, "dashboard")

Fragment C:
No Banner

MainFragment holding PagerAdapter:
override fun onPageSelected(p0: Int) {
                when (p0) {
                    1 -> {
                        HotmobReloadManager.instance.setCurrentPage("dashboard")
                    }
                    2 -> {
                        HotmobReloadManager.instance.setCurrentPage("notification")
                    }
                    else -> {
                        HotmobReloadManager.instance.setCurrentPage("home")
                    }
                }
            }
Both "dashboard", "notification", "home" are String only.

**Comment by yovenny** [comment]
found  “no ad return“  get exception above when hide banner、
**and now found that autoreload did't dispaly when fragment resume again ， although “Ad received, start rendering“ in log、**

**Comment by yovenny** [comment]
**did't show in adapter**
2019-09-09 10:52:37.965 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobSDKApplication] onActivityStarted()
2019-09-09 10:52:37.979 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobSDKApplication] Application moves to foreground.
2019-09-09 10:52:37.979 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> App resume. Without showing resume Interstitial.
2019-09-09 10:52:37.980 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show page [MovieGridRecyclerFragment{2e15e15 #0 id=0x7f0904a1}] banners.
2019-09-09 10:52:37.980 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show banner [eigaland_android_showing_test_movie_ad] on page [MovieGridRecyclerFragment{2e15e15 #0 id=0x7f0904a1}].
2019-09-09 10:52:37.981 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobSDKApplication] onActivityResumed()
2019-09-09 10:52:37.983 18206-18849/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] loadAd() starts now!
2019-09-09 10:52:37.983 18206-18849/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] HIDDEN -> LOADING
2019-09-09 10:52:37.984 18206-18206/gt.farm.eigaland.lab I/@#BaseHotmobFragment[98]: Visible -> MoviePagerFragment
2019-09-09 10:52:37.984 18206-18206/gt.farm.eigaland.lab I/@#BaseHotmobFragment[98]: Visible -> MovieGridRecyclerFragment
2019-09-09 10:52:37.985 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] onVisibilityChanged(VISIBLE)
2019-09-09 10:52:37.985 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] startTrackingVisibleArea()
2019-09-09 10:52:37.986 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_upcoming_test_movie_ad] onVisibilityChanged(VISIBLE)
2019-09-09 10:52:37.986 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_upcoming_test_movie_ad] startTrackingVisibleArea()
2019-09-09 10:52:37.999 18206-18849/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [AdRequest] <NETWORK> ad request exec() with url: https://ad.hot-mob.com/hmapi/v2/, params: {k=eigaland_android_showing_test_movie_ad, i=eigaland_android_showing_test_movie_ad, s=u1567996954639, oo=0, w=1080, app_ver=2.1.4.debug, app_id=gt.farm.eigaland.lab, make=Xiaomi, model=MI+6, os=Android, osv=8.0.0, sdk=2, ver=5.2.0, ss=8, scr_w=1080, scr_h=1920, lat=0.0, lon=0.0, token=4qOxsKdBtiF294O7Pcv5zlRNZPS0h0ya, _=1567997557}
2019-09-09 10:52:38.333 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Change page [MovieGridRecyclerFragment{2e15e15 #0 id=0x7f0904a1}] -> [MovieGridRecyclerFragment{2e15e15 #0 id=0x7f0904a1}].
2019-09-09 10:52:38.334 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show page [MovieGridRecyclerFragment{2e15e15 #0 id=0x7f0904a1}] banners.
2019-09-09 10:52:38.334 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobReloadManager] <AD_LOAD> Show banner [eigaland_android_showing_test_movie_ad] on page [MovieGridRecyclerFragment{2e15e15 #0 id=0x7f0904a1}].
2019-09-09 10:52:38.334 18206-18864/gt.farm.eigaland.lab W/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] loadAd() blocked, status: LOADING. Need to call hide() first before getting another ad
2019-09-09 10:52:39.923 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [AdRequest] <NETWORK> Success with model: 20980
2019-09-09 10:52:39.924 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] <AD_LOAD> [eigaland_android_showing_test_movie_ad] Ad received, start rendering
2019-09-09 10:52:39.924 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: **[HotmobBanner] [eigaland_android_showing_test_movie_ad] renderAd() render video ad
2019-09-09 10:52:39.965 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] LOADING -> LOADED
2019-09-09 10:52:39.966 18206-18206/gt.farm.eigaland.lab I/@#MovieBaseRecyclerFragme[431]: #F0 Loading hotmob video into adapter**
2019-09-09 10:52:39.981 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] onDetachedFromWindow()
2019-09-09 10:52:39.981 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] stopTrackingVisibleArea()
2019-09-09 10:52:39.982 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] onAttachedToWindow()
2019-09-09 10:52:39.982 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] startTrackingVisibleArea()
2019-09-09 10:52:39.983 18206-18206/gt.farm.eigaland.lab D/Hotmob-5.2.0-8: [HotmobBanner] [eigaland_android_showing_test_movie_ad] onVisibilityChanged(VISIBLE)

**Comment by hotmob-kenwong** [comment]
Hi yovenny,

From the above log I can see that the SDK reloads correctly and get a video ad. But it seems that the Banner is detached from the window when it is trying to load the video ad so the video does not load. It is not a reload problem but a compatibility problem between our video Banner and your RecycleView.

I suggest you to scroll up and down to ensure the Banner is on screen first. Our video Banner requests 1px height on screen in order to start rendering. I will also help verify this issue when you share a debug build with us.
